### PR TITLE
Request to merge Thai food into master

### PR DESCRIPTION
**Pull request by thanidacwn**
Already add menu and price

### CODE REVIEW

**Comment by PanupunJanin** [comment]
Checked, ready to merge

**Comment by ThanadolU** [comment]
You are doing a good work.

**Comment by Nantawat6510545543** [comment]
I checked, and there is no problem; it can be merged.

**Comment by CondricNay** [comment]
Okay to merge.

**Comment by thanidacwn** [comment]
Thank you for checking.

**Pull request merged**
